"""
senti_traffic_train.py
======================
Senti Traffic -- fine-tuning the detector on Indian footage.

senti_traffic_ml.py deliberately does no training: it loads weights and returns
Detections. This file is the other half -- it turns a labelled dataset into the
weights that file loads.

WHY THIS EXISTS
---------------
COCO has no auto-rickshaw class. Three-wheelers are a large share of Indian
traffic and pretrained YOLO scatters them across car / truck / motorcycle
depending on the angle. No amount of threshold tuning fixes that; the weights
have never seen the object. The only fix is fine-tuning on Indian footage with
`auto_rickshaw` as a real class.

The class list lives in senti_traffic_ml.SENTI_CLASSES and is written into
data.yaml from there, so the trained model and the inference layer cannot drift
apart.

DATASET LAYOUT (standard YOLO format)
-------------------------------------
    dataset/
      images/train/frame_0001.jpg      labels/train/frame_0001.txt
      images/val/frame_0100.jpg        labels/val/frame_0100.txt

Each label file is one line per object, normalised to 0-1:

    <class_id> <x_center> <y_center> <width> <height>

class_id is the INDEX INTO SENTI_CLASSES:

    0 person   1 bicycle   2 car   3 motorcycle   4 bus   5 truck   6 auto_rickshaw

An empty .txt means "this image genuinely contains none of our classes" -- that
is a valid and useful training sample, not a mistake. A *missing* .txt is a
different thing entirely: YOLO reads it as an empty label too, so an
unannotated image silently teaches the model that the vehicles in it are
background. `check` flags that.

USAGE
-----
    python senti_traffic_train.py check   --data path/to/dataset
    python senti_traffic_train.py train   --data path/to/dataset --epochs 100
    python senti_traffic_train.py val     --weights runs/senti/weights/best.pt --data path/to/dataset
    python senti_traffic_train.py export  --weights runs/senti/weights/best.pt

Run `check` first. It is fast, it is read-only, and every hour it costs you up
front is several hours of training it saves.
"""

from __future__ import annotations

import argparse
import collections
import random
import sys
from pathlib import Path
from typing import Optional

from senti_traffic_ml import SENTI_CLASSES, canonical_class

GENERATED_MARKER = "# GENERATED by senti_traffic_train.py"

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"}

# Recommended split when you have one undivided pile of images.
DEFAULT_VAL_FRACTION = 0.2


# ---------------------------------------------------------------------------
# 1. DATASET INSPECTION
# ---------------------------------------------------------------------------


def _is_generated_by_us(path: Path) -> bool:
    """True if we wrote this data.yaml, so its names are SENTI_CLASSES already."""
    if not path.is_file():
        return False
    head = path.read_text(encoding="utf-8", errors="replace")[:200]
    return GENERATED_MARKER in head


def read_yaml_names(path: Path) -> Optional[list[str]]:
    """Pull the `names:` list out of an existing data.yaml, or None.

    Uses PyYAML when available (ultralytics depends on it, so it usually is)
    and falls back to a deliberately dumb line parser that handles the two
    shapes ultralytics writes: `0: name` mappings and `- name` lists.
    """
    if not path.is_file():
        return None

    text = path.read_text(encoding="utf-8", errors="replace")
    try:
        import yaml  # noqa: PLC0415 -- optional, resolved at call time

        data = yaml.safe_load(text) or {}
        names = data.get("names")
        if isinstance(names, dict):
            return [str(names[k]) for k in sorted(names, key=lambda k: int(k))]
        if isinstance(names, list):
            return [str(n) for n in names]
        return None
    except ImportError:
        pass

    names, inside = [], False
    for raw in text.splitlines():
        if raw.strip().startswith("#"):
            continue
        if raw.rstrip().startswith("names:"):
            inside = True
            continue
        if inside:
            if raw[:1].strip() and not raw.startswith((" ", "\t", "-")):
                break                      # dedented: names block is over
            item = raw.strip()
            if not item:
                continue
            if item.startswith("- "):
                names.append(item[2:].strip())
            elif ":" in item:
                names.append(item.split(":", 1)[1].strip())
    return names or None


def _label_path(image_path: Path, root: Path, split: str) -> Path:
    """images/<split>/x.jpg -> labels/<split>/x.txt"""
    return root / "labels" / split / (image_path.stem + ".txt")


def _images_in(root: Path, split: str) -> list[Path]:
    directory = root / "images" / split
    if not directory.is_dir():
        return []
    return sorted(
        p for p in directory.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_SUFFIXES
    )


class DatasetReport:
    """What we found, and whether it is safe to train on."""

    def __init__(self) -> None:
        self.splits: dict[str, int] = {}
        self.class_counts: collections.Counter = collections.Counter()
        self.unlabelled: list[Path] = []
        self.empty_labels: list[Path] = []
        self.orphan_labels: list[Path] = []
        self.errors: list[str] = []          # hard stops
        self.warnings: list[str] = []        # train anyway, but know about it
        self.foreign_names: Optional[list[str]] = None   # dataset's own class list

    @property
    def total_images(self) -> int:
        return sum(self.splits.values())

    @property
    def total_boxes(self) -> int:
        return sum(self.class_counts.values())

    @property
    def ok(self) -> bool:
        return not self.errors


def check_dataset(root: Path, strict: bool = False) -> DatasetReport:
    """Validate a YOLO dataset without loading a single image pixel.

    Catches the failure modes that otherwise show up as a model that trains
    "successfully" for six hours and then detects nothing.
    """
    report = DatasetReport()

    if not root.is_dir():
        report.errors.append(f"dataset root does not exist: {root}")
        return report

    # A dataset that ships its own data.yaml was labelled against ITS class
    # list, not ours. Class IDs are just positions, so a plates dataset with
    # `0: number_plate` is bit-for-bit indistinguishable from `0: person` --
    # train on it blind and every plate box teaches the model what a pedestrian
    # looks like. Nothing crashes; the model just quietly comes out wrong.
    existing = read_yaml_names(root / "data.yaml")
    if existing is not None and not _is_generated_by_us(root / "data.yaml"):
        report.foreign_names = existing
        canon = [canonical_class(n) for n in existing]
        if list(existing) != list(SENTI_CLASSES):
            unknown = [n for n, c in zip(existing, canon) if c is None]
            report.errors.append(
                f"{root / 'data.yaml'} declares a different class list:\n"
                f"           theirs: {existing}\n"
                f"           ours:   {list(SENTI_CLASSES)}\n"
                f"         Class IDs are positions in that list, so training "
                f"this as-is silently relabels every box"
                + (f" (unmapped: {unknown})" if unknown else "")
                + ".\n         Remap the label files first -- see `remap`."
            )

    for split in ("train", "val"):
        images = _images_in(root, split)
        report.splits[split] = len(images)

        label_dir = root / "labels" / split
        seen_labels: set[Path] = set()

        for image in images:
            label = _label_path(image, root, split)
            if not label.exists():
                # NOT the same as an empty file: YOLO treats both as "no
                # objects here", so a forgotten annotation actively teaches the
                # model that these vehicles are background.
                report.unlabelled.append(image)
                continue

            seen_labels.add(label.resolve())
            lines = [
                ln.strip()
                for ln in label.read_text(encoding="utf-8", errors="replace").splitlines()
                if ln.strip()
            ]
            if not lines:
                report.empty_labels.append(label)
                continue

            for lineno, line in enumerate(lines, 1):
                parts = line.split()
                if len(parts) != 5:
                    report.errors.append(
                        f"{label}:{lineno}: expected 5 fields "
                        f"(class cx cy w h), got {len(parts)}"
                    )
                    continue
                try:
                    cls_id = int(float(parts[0]))
                    cx, cy, bw, bh = (float(v) for v in parts[1:])
                except ValueError:
                    report.errors.append(f"{label}:{lineno}: non-numeric value")
                    continue

                if not 0 <= cls_id < len(SENTI_CLASSES):
                    report.errors.append(
                        f"{label}:{lineno}: class id {cls_id} outside 0..{len(SENTI_CLASSES) - 1}. "
                        f"The dataset was probably exported against a different class list."
                    )
                    continue

                # YOLO wants normalised coordinates. Absolute pixel values are
                # the single most common export mistake and they train to
                # garbage rather than crashing.
                if not all(0.0 <= v <= 1.0 for v in (cx, cy, bw, bh)):
                    report.errors.append(
                        f"{label}:{lineno}: coordinates outside 0-1 "
                        f"({cx:.1f} {cy:.1f} {bw:.1f} {bh:.1f}). "
                        f"These look like pixels -- YOLO needs them normalised."
                    )
                    continue
                if bw <= 0 or bh <= 0:
                    report.errors.append(f"{label}:{lineno}: zero-area box")
                    continue

                report.class_counts[SENTI_CLASSES[cls_id]] += 1

        if label_dir.is_dir():
            for label in label_dir.glob("*.txt"):
                if label.resolve() not in seen_labels:
                    report.orphan_labels.append(label)

    # -- judgement ----------------------------------------------------------

    if report.splits.get("train", 0) == 0:
        report.errors.append(
            f"no training images found under {root / 'images' / 'train'}"
        )
    if report.splits.get("val", 0) == 0:
        report.errors.append(
            f"no validation images found under {root / 'images' / 'val'}. "
            f"Without a val split there is no way to tell learning from "
            f"memorising -- use `split` to carve one out."
        )

    if report.unlabelled:
        message = (
            f"{len(report.unlabelled)} image(s) have no label file. YOLO reads "
            f"those as 'contains nothing', which trains the model to ignore "
            f"whatever is in them."
        )
        (report.errors if strict else report.warnings).append(message)
    if report.orphan_labels:
        report.warnings.append(
            f"{len(report.orphan_labels)} label file(s) have no matching image "
            f"(ignored during training)"
        )

    for name in SENTI_CLASSES:
        count = report.class_counts[name]
        if count == 0:
            report.warnings.append(
                f"class '{name}' has zero examples -- the model cannot learn it, "
                f"and TrafficDetector.missing_classes will report it at runtime"
            )
        elif count < 50:
            report.warnings.append(
                f"class '{name}' has only {count} example(s); expect unreliable "
                f"detections below a few hundred"
            )

    if report.class_counts:
        most = report.class_counts.most_common()
        top_name, top_count = most[0]
        rare = [(n, c) for n, c in most if c > 0][-1]
        if rare[1] and top_count / rare[1] > 20:
            report.warnings.append(
                f"heavy class imbalance: '{top_name}' has {top_count} boxes vs "
                f"'{rare[0]}' with {rare[1]} ({top_count / rare[1]:.0f}x). The "
                f"rare class will be under-detected; consider more footage of it."
            )

    return report


def print_report(report: DatasetReport) -> None:
    print(f"\nimages   train={report.splits.get('train', 0)}  "
          f"val={report.splits.get('val', 0)}  total={report.total_images}")
    print(f"boxes    {report.total_boxes}")

    if report.class_counts:
        if report.foreign_names:
            # Without this the table reads as fact. It is not: these counts are
            # the dataset's own IDs looked up in OUR list, which is precisely
            # the mistranslation the error below is about.
            print(f"\nper class -- MISREAD ON PURPOSE, see the error below."
                  f"\n(IDs interpreted as {list(SENTI_CLASSES)},"
                  f"\n but this dataset labelled them {report.foreign_names})")
        else:
            print("\nper class:")
        width = max(len(n) for n in SENTI_CLASSES)
        for name in SENTI_CLASSES:
            count = report.class_counts[name]
            share = 100.0 * count / report.total_boxes if report.total_boxes else 0.0
            bar = "#" * int(share / 2)
            flag = "" if count else "   <- absent"
            print(f"  {name:<{width}}  {count:6d}  {share:5.1f}%  {bar}{flag}")

    if report.empty_labels:
        print(f"\n{len(report.empty_labels)} deliberately empty label(s) "
              f"(valid background samples)")

    for warning in report.warnings:
        print(f"\n[warn]  {warning}")
    for error in report.errors:
        print(f"\n[ERROR] {error}")

    print("\n" + ("dataset looks trainable" if report.ok
                  else "FIX THE ERRORS ABOVE BEFORE TRAINING"))


# ---------------------------------------------------------------------------
# 2. SPLIT
# ---------------------------------------------------------------------------


def split_dataset(root: Path, val_fraction: float, seed: int = 0,
                  dry_run: bool = True) -> None:
    """Move a fraction of images/train (and their labels) into images/val.

    Deterministic given `seed`, so re-running does not reshuffle what is
    already split. Defaults to a dry run -- pass --apply to actually move.
    """
    train_images = _images_in(root, "train")
    if not train_images:
        raise SystemExit(f"nothing to split: no images under {root / 'images' / 'train'}")

    existing_val = len(_images_in(root, "val"))
    if existing_val:
        print(f"[note] images/val already holds {existing_val} image(s); "
              f"splitting more on top of it")

    rng = random.Random(seed)
    shuffled = sorted(train_images)
    rng.shuffle(shuffled)
    cut = int(len(shuffled) * val_fraction)
    moving = shuffled[:cut]

    if not moving:
        raise SystemExit(f"val_fraction {val_fraction} rounds to zero images")

    print(f"{'would move' if dry_run else 'moving'} {len(moving)} of "
          f"{len(train_images)} image(s) into val ({val_fraction:.0%})")
    if dry_run:
        print("dry run -- pass --apply to perform the move")
        return

    (root / "images" / "val").mkdir(parents=True, exist_ok=True)
    (root / "labels" / "val").mkdir(parents=True, exist_ok=True)

    for image in moving:
        image.rename(root / "images" / "val" / image.name)
        label = _label_path(image, root, "train")
        if label.exists():
            label.rename(root / "labels" / "val" / label.name)

    print("done")


# ---------------------------------------------------------------------------
# 3. data.yaml
# ---------------------------------------------------------------------------


def write_data_yaml(root: Path, path: Path | None = None) -> Path:
    """Generate the data.yaml ultralytics reads, from SENTI_CLASSES.

    Generated rather than hand-written on purpose: a hand-edited class list that
    disagrees with SENTI_CLASSES produces a model whose class 6 is not what the
    inference layer thinks class 6 is, and nothing anywhere will tell you.
    """
    path = path or (root / "data.yaml")

    # Never overwrite someone else's class list. Doing so is silent and
    # unrecoverable-looking: the labels still parse, training still runs, and
    # the resulting model is wrong in a way no error message mentions.
    existing = read_yaml_names(path)
    if existing is not None and not _is_generated_by_us(path):
        if list(existing) != list(SENTI_CLASSES):
            raise SystemExit(
                f"refusing to overwrite {path}\n"
                f"  it declares {existing}, we use {list(SENTI_CLASSES)}.\n"
                f"  Run `remap` to convert the labels onto our class list first."
            )

    names = "\n".join(f"  {i}: {n}" for i, n in enumerate(SENTI_CLASSES))
    path.write_text(
        f"{GENERATED_MARKER} -- do not hand-edit.\n"
        "# The class list mirrors senti_traffic_ml.SENTI_CLASSES; change it there.\n"
        f"path: {root.resolve().as_posix()}\n"
        "train: images/train\n"
        "val: images/val\n"
        f"nc: {len(SENTI_CLASSES)}\n"
        "names:\n"
        f"{names}\n",
        encoding="utf-8",
    )
    return path


# ---------------------------------------------------------------------------
# 3b. REMAP -- fold a foreign dataset onto SENTI_CLASSES
# ---------------------------------------------------------------------------


def remap_dataset(src: Path, dst: Path, extra_map: dict[str, str],
                  drop_unmapped: bool, dry_run: bool = True) -> None:
    """Rewrite a dataset's label IDs from its own class list onto ours.

    Every public dataset numbers its classes differently -- IDD, DriveIndia and
    a plates set all use `0` for three unrelated things. This is the one place
    that difference gets resolved, by NAME, before any training happens.

    Images are hard-linked where the filesystem allows it (instant, no extra
    disk) and copied otherwise. The source tree is never modified.
    """
    src_names = read_yaml_names(src / "data.yaml")
    if src_names is None:
        raise SystemExit(
            f"no data.yaml with a names: list under {src}\n"
            f"  Without it there is no way to know what the label IDs mean."
        )

    # source id -> our id, resolved by name
    id_map: dict[int, int] = {}
    unmapped: list[str] = []
    for src_id, raw in enumerate(src_names):
        override = extra_map.get(raw.strip().lower())
        name = override or canonical_class(raw)
        if name is None or name not in SENTI_CLASSES:
            unmapped.append(raw)
            continue
        id_map[src_id] = SENTI_CLASSES.index(name)

    print(f"source classes: {src_names}")
    for src_id, our_id in sorted(id_map.items()):
        print(f"  {src_id:>2} {src_names[src_id]:<20} -> {our_id:>2} {SENTI_CLASSES[our_id]}")
    for raw in unmapped:
        print(f"  -- {raw:<20} -> DROPPED (no equivalent in SENTI_CLASSES)")

    if unmapped and not drop_unmapped:
        raise SystemExit(
            f"\n{len(unmapped)} class(es) have no equivalent: {unmapped}\n"
            f"  Either pass --map '{unmapped[0]}=motorcycle' style overrides,\n"
            f"  or --drop-unmapped to discard those boxes. Refusing to guess.\n"
            f"  NOTE: dropping a class turns its objects into background, which\n"
            f"  actively teaches the model to ignore them. That is right for\n"
            f"  number plates (a separate detector) and wrong for, say, a\n"
            f"  'rider' class you actually care about."
        )
    if not id_map:
        raise SystemExit("nothing to remap: no source class matched SENTI_CLASSES")

    total_in = total_out = images_done = 0
    for split in ("train", "val"):
        for image in _images_in(src, split):
            label_src = _label_path(image, src, split)
            kept: list[str] = []
            if label_src.exists():
                for line in label_src.read_text(encoding="utf-8",
                                                errors="replace").splitlines():
                    parts = line.split()
                    if len(parts) != 5:
                        continue
                    total_in += 1
                    src_id = int(float(parts[0]))
                    if src_id not in id_map:
                        continue
                    kept.append(" ".join([str(id_map[src_id]), *parts[1:]]))
                    total_out += 1

            images_done += 1
            if dry_run:
                continue

            (dst / "images" / split).mkdir(parents=True, exist_ok=True)
            (dst / "labels" / split).mkdir(parents=True, exist_ok=True)
            image_dst = dst / "images" / split / image.name
            if not image_dst.exists():
                try:
                    import os

                    os.link(image, image_dst)      # same volume: free
                except OSError:
                    import shutil

                    shutil.copy2(image, image_dst)
            # Always write the .txt, even when empty: an absent label and an
            # empty one mean the same thing to YOLO, but an explicit empty file
            # documents that we looked and there was nothing to keep.
            (dst / "labels" / split / (image.stem + ".txt")).write_text(
                "\n".join(kept) + ("\n" if kept else ""), encoding="utf-8")

    verb = "would write" if dry_run else "wrote"
    print(f"\n{verb} {images_done} image(s); boxes {total_in} -> {total_out} "
          f"({total_in - total_out} dropped)")

    if unmapped and total_in > total_out:
        share = 100.0 * (total_in - total_out) / total_in
        shown = ", ".join(unmapped[:4]) + ("..." if len(unmapped) > 4 else "")
        print(
            f"\n[warn] {share:.0f}% of boxes were dropped, from: {shown}\n"
            f"       Those objects are now unlabelled *background* in images that\n"
            f"       still contain them, which actively trains the model to ignore\n"
            f"       them. Fine for scenery; check the list above for anything a\n"
            f"       rule depends on and re-run with --map 'THEIRS=OURS'."
        )
    if dry_run:
        print("dry run -- pass --apply to write")
    else:
        write_data_yaml(dst)
        print(f"remapped dataset ready: {dst}")
        print(f"next: python senti_traffic_train.py check --data {dst}")


# ---------------------------------------------------------------------------
# 4. TRAIN / VAL / EXPORT
# ---------------------------------------------------------------------------


def train(args) -> None:
    from ultralytics import YOLO

    root = Path(args.data).expanduser().resolve()

    report = check_dataset(root, strict=args.strict)
    print_report(report)
    if not report.ok:
        raise SystemExit("\nrefusing to train on a dataset with errors "
                         "(use `check` to inspect, fix, then retry)")

    yaml_path = write_data_yaml(root)
    print(f"\n[senti] wrote {yaml_path}")

    model = YOLO(args.weights)
    print(f"[senti] fine-tuning {args.weights} -> {len(SENTI_CLASSES)} classes")

    model.train(
        data=str(yaml_path),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=args.project,
        name=args.name,
        exist_ok=True,
        patience=args.patience,
        seed=args.seed,

        # -- augmentation, tuned for traffic cameras ------------------------
        # A fixed pole sees one scene all day, so the model must not learn
        # "vehicles appear in the lower-left". Translation and scale jitter
        # matter more here than colour tricks.
        degrees=args.degrees,     # small: traffic cameras are roughly level
        translate=0.1,
        scale=0.5,                # distant vs near vehicles differ hugely in size
        fliplr=0.0 if args.no_flip else 0.5,
        mosaic=1.0,               # dense multi-vehicle scenes: this helps a lot
        close_mosaic=10,          # ...but turn it off at the end to match reality
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,                # day/night and glare variation
    )

    best = Path(args.project) / args.name / "weights" / "best.pt"
    print(f"\n[senti] best weights: {best}")
    print(f"[senti] use them with: "
          f"python senti_traffic_ml.py --source clip.mp4 --weights {best}")


def validate(args) -> None:
    from ultralytics import YOLO

    root = Path(args.data).expanduser().resolve()
    yaml_path = write_data_yaml(root)

    model = YOLO(args.weights)
    metrics = model.val(data=str(yaml_path), imgsz=args.imgsz, device=args.device)

    print("\nper-class AP50 (higher is better; below ~0.5 is not deployable):")
    try:
        names = model.names
        for i, ap in enumerate(metrics.box.ap50):
            label = names[i] if isinstance(names, dict) else names[i]
            print(f"  {label:<16} {ap:.3f}")
    except Exception:  # noqa: BLE001 -- metrics shape varies across versions
        print("  (per-class breakdown unavailable; see the table above)")


def export(args) -> None:
    from ultralytics import YOLO

    model = YOLO(args.weights)
    out = model.export(format=args.format, imgsz=args.imgsz, half=args.half)
    print(f"[senti] exported -> {out}")


# ---------------------------------------------------------------------------
# 5. CLI
# ---------------------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Senti Traffic -- dataset checks and fine-tuning")
    sub = ap.add_subparsers(dest="command", required=True)

    c = sub.add_parser("check", help="validate a dataset (read-only, fast)")
    c.add_argument("--data", required=True, help="dataset root")
    c.add_argument("--strict", action="store_true",
                   help="treat unlabelled images as errors, not warnings")

    s = sub.add_parser("split", help="carve a val split out of images/train")
    s.add_argument("--data", required=True)
    s.add_argument("--val-fraction", type=float, default=DEFAULT_VAL_FRACTION)
    s.add_argument("--seed", type=int, default=0)
    s.add_argument("--apply", action="store_true",
                   help="actually move files (default is a dry run)")

    r = sub.add_parser("remap", help="convert a dataset's class IDs onto SENTI_CLASSES")
    r.add_argument("--src", required=True, help="source dataset root (with data.yaml)")
    r.add_argument("--dst", required=True, help="output dataset root")
    r.add_argument("--map", action="append", default=[], metavar="THEIRS=OURS",
                   help="force a mapping, e.g. --map 'vehicle fallback=car'")
    r.add_argument("--drop-unmapped", action="store_true",
                   help="discard boxes whose class has no equivalent")
    r.add_argument("--apply", action="store_true",
                   help="actually write (default is a dry run)")

    t = sub.add_parser("train", help="fine-tune on the dataset")
    t.add_argument("--data", required=True)
    t.add_argument("--weights", default="yolo11s.pt",
                   help="starting checkpoint (yolo11n/s/m/l)")
    t.add_argument("--epochs", type=int, default=100)
    t.add_argument("--imgsz", type=int, default=960,
                   help="train at the resolution you will infer at; 960 helps "
                        "distant two-wheelers")
    t.add_argument("--batch", type=int, default=-1, help="-1 = auto-fit to VRAM")
    t.add_argument("--device", default=None, help="cuda | cpu | 0")
    t.add_argument("--workers", type=int, default=4)
    t.add_argument("--project", default="runs")
    t.add_argument("--name", default="senti")
    t.add_argument("--patience", type=int, default=25,
                   help="early stop after N epochs without improvement")
    t.add_argument("--seed", type=int, default=0)
    t.add_argument("--degrees", type=float, default=5.0)
    t.add_argument("--no-flip", action="store_true",
                   help="disable horizontal flip (use for one-way-traffic scenes)")
    t.add_argument("--strict", action="store_true")

    v = sub.add_parser("val", help="score a checkpoint against the val split")
    v.add_argument("--weights", required=True)
    v.add_argument("--data", required=True)
    v.add_argument("--imgsz", type=int, default=960)
    v.add_argument("--device", default=None)

    e = sub.add_parser("export", help="export for deployment")
    e.add_argument("--weights", required=True)
    e.add_argument("--format", default="onnx")
    e.add_argument("--imgsz", type=int, default=960)
    e.add_argument("--half", action="store_true")

    args = ap.parse_args()

    if args.command == "check":
        report = check_dataset(Path(args.data).expanduser().resolve(), args.strict)
        print_report(report)
        sys.exit(0 if report.ok else 1)
    elif args.command == "split":
        split_dataset(Path(args.data).expanduser().resolve(),
                      args.val_fraction, args.seed, dry_run=not args.apply)
    elif args.command == "remap":
        overrides = {}
        for pair in args.map:
            if "=" not in pair:
                raise SystemExit(f"--map needs THEIRS=OURS, got {pair!r}")
            theirs, ours = pair.split("=", 1)
            ours = ours.strip()
            if ours not in SENTI_CLASSES:
                raise SystemExit(
                    f"--map target {ours!r} is not one of {list(SENTI_CLASSES)}")
            overrides[theirs.strip().lower()] = ours
        remap_dataset(Path(args.src).expanduser().resolve(),
                      Path(args.dst).expanduser().resolve(),
                      overrides, args.drop_unmapped, dry_run=not args.apply)
    elif args.command == "train":
        train(args)
    elif args.command == "val":
        validate(args)
    elif args.command == "export":
        export(args)


if __name__ == "__main__":
    main()
