"""
handoff.py
==========
Refresh the machine-readable half of HANDOFF.md.

WHY
HANDOFF.md is the continuity document -- what a fresh session reads first. Half
of it is judgement (findings, constraints, decisions) and must stay hand-written.
The other half is pure state: what's committed, what isn't, which rules exist,
what the model scored. That half goes stale within hours and is exactly the part
a reader most needs to trust.

So: everything between the AUTO markers is regenerated from the repo itself.
Everything outside them is left alone.

USAGE
    python scripts/handoff.py            # refresh in place
    python scripts/handoff.py --check    # report staleness, change nothing
"""

from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HANDOFF = ROOT / 'HANDOFF.md'
BEGIN = '<!-- AUTO:BEGIN -- regenerated by scripts/handoff.py, do not edit by hand -->'
END = '<!-- AUTO:END -->'


def sh(*args: str) -> str:
    try:
        return subprocess.run(args, cwd=ROOT, capture_output=True,
                              text=True, timeout=30).stdout.strip()
    except Exception:
        return ''


def metrics() -> list[str]:
    csv_path = ROOT / 'results' / 'driveindia' / 'results.csv'
    if not csv_path.exists():
        return ['_No `results/driveindia/results.csv` — model not trained in this tree._']
    rows = list(csv.DictReader(open(csv_path, newline='', encoding='utf-8')))
    if not rows:
        return ['_results.csv is empty._']

    def val(r, key):
        for k in r:
            if k.strip() == key:
                try:
                    return float(r[k])
                except (TypeError, ValueError):
                    return None
        return None

    best_i = max(range(len(rows)), key=lambda i: val(rows[i], 'metrics/mAP50(B)') or 0)
    b = rows[best_i]
    return [
        f'Trained: **{len(rows)} epochs**, best at **epoch {best_i + 1}**.',
        '',
        '| | mAP@50 | mAP@50-95 | precision | recall |',
        '|---|---|---|---|---|',
        f'| validation (best epoch) | {val(b, "metrics/mAP50(B)"):.4f} | '
        f'{val(b, "metrics/mAP50-95(B)"):.4f} | {val(b, "metrics/precision(B)"):.4f} | '
        f'{val(b, "metrics/recall(B)"):.4f} |',
        '',
        '> ⚠️ Those are **validation** figures. The reportable **test** number is '
        '**0.703 mAP@50** — see `results/driveindia/generalisation_gap.png`.',
    ]


def rules() -> list[str]:
    sys.path.insert(0, str(ROOT))
    try:
        from senti.rules import RULE_REGISTRY, available_rules
    except Exception as e:
        return [f'_Could not import the rule registry: {e}_']
    out = ['| Rule | Applies to | Requires | Legal basis |', '|---|---|---|---|']
    for n in available_rules():
        c = RULE_REGISTRY[n]
        applies = ', '.join(c.applies_to[:4]) + ('…' if len(c.applies_to) > 4 else '')
        req = ', '.join(c.requires) or '—'
        out.append(f'| `{n}` | {applies} | {req} | {c.mv_act_section or "—"} |')
    return out


def build() -> str:
    dirty = sh('git', 'status', '--porcelain')
    log = sh('git', 'log', '--oneline', '-8')
    branch = sh('git', 'rev-parse', '--abbrev-ref', 'HEAD') or '?'
    remote = sh('git', 'remote', 'get-url', 'origin') or '(no remote)'
    unpushed = sh('git', 'log', '--oneline', '@{u}..HEAD') if remote != '(no remote)' else ''

    py = sorted(p.relative_to(ROOT).as_posix()
                for p in (ROOT / 'senti').rglob('*.py') if p.name != '__init__.py')
    scripts = sorted(p.name for p in (ROOT / 'scripts').glob('*.py'))
    configs = sorted(p.name for p in (ROOT / 'config').glob('*.yaml'))
    videos = sorted(p.name for p in (ROOT / 'data' / 'videos').glob('*')) \
        if (ROOT / 'data' / 'videos').is_dir() else []
    evidence = len(list((ROOT / 'data' / 'evidence').glob('*'))) \
        if (ROOT / 'data' / 'evidence').is_dir() else 0
    weights = [f'{p.relative_to(ROOT).as_posix()} ({p.stat().st_size / 1e6:.0f} MB)'
               for p in ROOT.rglob('best.pt')]

    L: list[str] = [BEGIN, '']
    L += [f'*State refreshed {datetime.now():%d %B %Y, %H:%M} by `scripts/handoff.py`.*', '']

    L += ['### Repository', '',
          f'- branch `{branch}` → {remote}',
          f'- **{"CLEAN" if not dirty else str(len(dirty.splitlines())) + " uncommitted change(s)"}**']
    if unpushed:
        L.append(f'- ⚠️ **{len(unpushed.splitlines())} commit(s) not pushed**')
    L += ['', '```', log or '(no commits)', '```', '']

    if dirty:
        L += ['### ⚠️ Uncommitted', '', '```', dirty, '```',
              '', '_Confirm with the user before committing these — some are held back deliberately._', '']

    L += ['### Model', ''] + metrics() + ['']
    if weights:
        L += ['Weights on disk (gitignored via `*.pt`):', ''] + \
             [f'- `{w}`' for w in weights] + ['']

    L += ['### Rules implemented', ''] + rules() + ['']

    L += ['### Code', '',
          f'**`senti/`** ({len(py)} modules): ' + ', '.join(f'`{p}`' for p in py), '',
          f'**`scripts/`**: ' + ', '.join(f'`{s}`' for s in scripts), '',
          f'**`config/`**: ' + ', '.join(f'`{c}`' for c in configs), '']

    L += ['### Test assets', '',
          f'- videos: {", ".join(f"`{v}`" for v in videos) if videos else "_none_"}',
          f'- evidence packages on disk: {evidence}', '']

    L += [END]
    return '\n'.join(L)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='report whether the block is stale; write nothing')
    args = ap.parse_args()

    if not HANDOFF.exists():
        raise SystemExit(f'{HANDOFF} not found')

    text = HANDOFF.read_text(encoding='utf-8')
    block = build()

    if BEGIN in text and END in text:
        start, end = text.index(BEGIN), text.index(END) + len(END)
        current = text[start:end]
        if args.check:
            same = current.split('\n', 3)[3:] == block.split('\n', 3)[3:]
            print('HANDOFF.md auto-block is ' + ('current.' if same else 'STALE — run without --check.'))
            return
        text = text[:start] + block + text[end:]
    else:
        if args.check:
            print('HANDOFF.md has no AUTO block yet — run without --check to insert one.')
            return
        # insert after the intro, before the first '## '
        marker = text.index('\n## ') if '\n## ' in text else len(text)
        text = text[:marker] + '\n' + block + '\n' + text[marker:]

    HANDOFF.write_text(text, encoding='utf-8')
    print(f'refreshed the auto block in {HANDOFF.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
